services:
  db:
    image: postgres
    volumes:
      # persist postgres data in a volume
      - "db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=sample"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db: