# Generated by Django 4.2.5 on 2023-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_attachment_created_at_attachment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time_accumulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
