# Generated by Django 4.2.5 on 2023-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_created_at_profile_gender_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
